### ISSUE TITLE
Server side streaming buffering clarification

### ISSUE THREAD

**Issue by stefandanaita** [hyperium/tonic#378]
Hello guys! I've implemented a gRPC server that's doing server side streaming and I have a question around the channel's buffer size.

Setting the buffer size to 4, like it currently is in the documentation (`let (mut tx, rx) = mpsc::channel(req.buffer_size as usize);`) will push the streams to the client in bursts of 5.

However, what I'm currently trying to achieve is "real-time" between when the stream is sent to the sink and when it actually gets pushed to the client, i.e no buffering. And so I tried setting the buffer to 0, hoping that the stream will get pushed as soon as the sink is flushed (which is done automatically by calling `tx.send(...).await;`). No luck though, by doing it this way, a stream only gets pushed to the client as soon as the next stream is sent to the sink.

I would expect that by setting the buffer to 0, the streams don't get buffered at all. Am I doing something wrong? How can I achieve what I am looking for with tonic?

To replicate this, you can checkout this mock repository - [mock-grpc](https://github.com/stefandanaita/mock-grpc) and send the following request:
```
{
  "number_of_streams": 5,
  "buffer_size": 0,
  "ttl": 10
}
```

In the ideal scenario, you should see all the 5 streams coming instantly and the connection to be dropped by the server after 10 seconds. However, you will only get 4 streams instantly and the 5th stream only when the connection is dropped.

This means that by setting the buffer size to 0, every stream only gets pushed out when another one is processed by the sink, and the last one is pushed out when the server ends the request.

Thanks a lot for your help!

**Comment by stefandanaita** [comment]
Lucio suggested on Discord to use unbounded channels: [unbounded channels branch](https://github.com/stefandanaita/mock-grpc/tree/unbounded). However, with this approach it's even worse than bounded channels with buffer = 0.

In the bounded channels case, the number of streams buffered are equal to whatever you set as the channel buffer + 1. For unbounded channels, weirdly enough I only get the streams (all of them at once) on the client as soon as the server closes the connection.

**Comment by LucioFranco** [comment]
@seanmonstar is hyper doing any extra buffering here? 

This might also have to do with h2 window size. You may want to consider playing around with that.

**Comment by seanmonstar** [comment]
I'm sorry I don't fully understand the context. Hyper does have a small buffer to handle the HTTP/2 framing, and if a stream runs of available flow control, it will try to stop pulling from the user's body stream, to propagate back pressure, until the peer gives some more window space.

**Comment by LucioFranco** [comment]
From tonics side we just basically map prost::Message -> impl Buf and pass to hyper.

**Comment by stefandanaita** [comment]
> I'm sorry I don't fully understand the context. Hyper does have a small buffer to handle the HTTP/2 framing, and if a stream runs of available flow control, it will try to stop pulling from the user's body stream, to propagate back pressure, until the peer gives some more window space.

It's unlikely that the stream runs out of available flow control. At least not for my mock example repository above where I'm basically streaming 5 tiny streams. It's weird that the number of streams buffered when using `mpsc::channel(<VALUE>)` is equal to `VALUE + 1`.

So for `mpsc::channel(5)`, we'll have 6 streams buffered and the 7th stream will trigger the first 6 to be sent
..for `mpsc::channel(1)`, we'll have 2 streams buffered, 3rd triggering the first 2..
and for `mpsc::channel(0)`, there's always 1 stream buffered 😢 

And when using unbounded channels, which to my understanding should stream right away, nothing is streamed until the connection is ended by the server.

**Comment by LucioFranco** [comment]
@stefandanaita do you have a demo I could try with a client that shows the behavior? Another thing that would be helpful is to turn on logs and get the `RUST_LOG=h2=debug` logs.

**Comment by fluxxu** [comment]
@LucioFranco 
I can reproduce the issue with payload
```json
{
  "number_of_streams": 5,
  "buffer_size": 0,
  "ttl": 10
}
```

here is the log: (RUST_LOG=h2=debug)
```
fluxxu@Fluxs-MacBook-Pro mock-grpc % cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/mock-grpc`
50052
GO FOR LAUNCH
Jul 13 15:49:27.304 DEBUG h2::codec::framed_write: send; frame=Settings { flags: (0x0), initial_window_size: 1048576, max_frame_size: 16384 }    
Jul 13 15:49:27.315 DEBUG h2::codec::framed_read: received; frame=Settings { flags: (0x0), enable_push: 0, max_concurrent_streams: 0, initial_window_size: 4194304, max_frame_size: 4194304, max_header_list_size: 8192 }    
Jul 13 15:49:27.315 DEBUG h2::codec::framed_write: send; frame=Settings { flags: (0x1: ACK) }    
Jul 13 15:49:27.315 DEBUG h2::codec::framed_read: received; frame=WindowUpdate { stream_id: StreamId(0), size_increment: 4128769 }    
Jul 13 15:49:27.315 DEBUG h2::codec::framed_read: received; frame=Ping { ack: false, payload: [0, 0, 0, 0, 0, 0, 0, 0] }    
Jul 13 15:49:27.315 DEBUG h2::codec::framed_write: send; frame=Ping { ack: true, payload: [0, 0, 0, 0, 0, 0, 0, 0] }    
Jul 13 15:49:27.315 DEBUG h2::codec::framed_read: received; frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }    
Jul 13 15:49:27.316 DEBUG h2::codec::framed_read: received; frame=WindowUpdate { stream_id: StreamId(1), size_increment: 5 }    
Jul 13 15:49:27.316 DEBUG h2::codec::framed_read: received; frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }    
Jul 13 15:49:27.316 DEBUG h2::codec::framed_read: received; frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5 }    
Jul 13 15:49:27.316 DEBUG h2::codec::framed_write: send; frame=WindowUpdate { stream_id: StreamId(0), size_increment: 983041 }    
Sending stream 1...
Jul 13 15:49:27.318 DEBUG h2::codec::framed_write: send; frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }    
Sent stream 1 in 815000 nanos
Sending stream 2...
Jul 13 15:49:27.318 DEBUG h2::codec::framed_write: send; frame=Data { stream_id: StreamId(1) }    
Sent stream 2 in 612000 nanos
Sending stream 3...
Jul 13 15:49:27.319 DEBUG h2::codec::framed_write: send; frame=Data { stream_id: StreamId(1) }    
Sent stream 3 in 552000 nanos
Sending stream 4...
Jul 13 15:49:27.320 DEBUG h2::codec::framed_write: send; frame=Data { stream_id: StreamId(1) }    
Sent stream 4 in 533000 nanos
Sending stream 5...
Jul 13 15:49:27.320 DEBUG h2::codec::framed_write: send; frame=Data { stream_id: StreamId(1) }    
Sent stream 5 in 533000 nanos
Jul 13 15:49:38.318 DEBUG h2::codec::framed_write: send; frame=Data { stream_id: StreamId(1) }    
Jul 13 15:49:38.318 DEBUG h2::codec::framed_write: send; frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }  
```

**Comment by LucioFranco** [comment]
@fluxxu do you have code available for this?

**Comment by fluxxu** [comment]
> @fluxxu do you have code available for this?

Here 
https://github.com/fluxxu/mock-grpc.git

Server:
```
cargo run --bin server
```

Client:
```
cargo run --bin=client
```

**Comment by stefandanaita** [comment]
Thanks for jumping in @fluxxu! @LucioFranco have you had a chance to try Fluxxu's mock code?

**Comment by LucioFranco** [comment]
Hey @stefandanaita and @fluxxu thanks for the reproduction! So I can reproduce the issue but nothing is poking out as obvious, I am going to have to dig a bit deeper into h2 and see what is going on. From what I can tell the rx end of the stream is not getting polled after notifying that there is a new message.

cc @seanmonstar we should take a look together when you have some time.

**Comment by stefandanaita** [comment]
Hey @LucioFranco! Have you had any time to look into this? 😢

**Comment by LucioFranco** [comment]
I have not had a chance yet, I pinged @seanmonstar to take a look, otherwise, I will try and look next week when I get some time. Work has been quite busy for me sorry :(

**Comment by stefandanaita** [comment]
Hello @LucioFranco! I know you're pretty busy, but if you find some time at some point, this issue is still valid and could do with some love 😄

**Comment by LucioFranco** [comment]
@stefandanaita sorry, let me add this to the list of priorities, hopefulyl will get there soon. I am trying to focus on hyper as long as this is not blocking you?

**Comment by stefandanaita** [comment]
I've temporarily "solved" this by calling `tx.send(..)` twice (the 2nd call being fake and its only purpose is to trigger the initial one). Far from ideal, but it's not blocking me either.

**Comment by LucioFranco** [comment]
@stefandanaita if you're still having this issue, it would be handy to see if we could reproduce this directly with hyper to isolate if its something in tonic or not.

**Comment by cjhopman** [comment]
I updated all the dependencies in @fluxxu 's repro and it seems to have been fixed. The client now takes an arg for how many responses and ttl and then both print the elapsed time sending/receiving each item.

https://github.com/cjhopman/mock-grpc

Run with:
```
cargo run --bin server
cargo run --bin client -- 1 3 # 1 response item, 3s ttl
cargo run --bin client -- 100 3 # 100 response item, 3s ttl
```

**Comment by LucioFranco** [comment]
Cool thanks for looking I guess we can close it then.

**Comment by StrikeW** [comment]
Sorry to bother you, since I cannot get access to Discord. I want to analyze the http packets of my tonic program but when I run it with `RUST_LOG=debug cargo run --bin server` and `RUST_LOG=debug cargo run --bin client`, there is no logs print out.

How can I enable the debug log printing (especially for h2)? The following is my Cargo.toml file, and the repo is [here](https://github.com/StrikeW/grpc-example).

```
[package]
name = "rust-lab"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
async-stream = "0.3"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.7"
prost = "0.10"

[build-dependencies]
tonic-build = "0.7"
```

**Comment by matt-deboer** [comment]
I note this was marked fixed about a year ago, but I'm still seeing this behavior with tonic `0.9.2` and tokio `1.25`..any details on what the fix was?

Specifically, I'm still seeing the same behavior as mentioned by @stefandanaita:

> It's unlikely that the stream runs out of available flow control. At least not for my mock example repository above where I'm basically streaming 5 tiny streams. It's weird that the number of streams buffered when using mpsc::channel(<VALUE>) is equal to VALUE + 1.

I'm sending a stream of jpeg images, ~ 48k each, and seeing the pattern on the client side is to receive N+1 frames in a bundle, for whatever value of N I plug in when creating the channel ( `mpsc::channel(N)`)...any ideas how I can get immediate send on a stream?

Here's a sample of the logs with `RUST_LOG=h2=debug`:
```
2023-04-26T04:01:44.179204Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.179479Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.179587Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15636 }
2023-04-26T04:01:44.179673Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.179890Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.180926Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 746 }
2023-04-26T04:01:44.181706Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.181890Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 14885 }
2023-04-26T04:01:44.367745Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.367862Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.367899Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.368007Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.368067Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.368973Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.369058Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.369165Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.369212Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15749 }
2023-04-26T04:01:44.369254Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.369457Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.370040Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 633 }
2023-04-26T04:01:44.370466Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.370632Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15192 }
2023-04-26T04:01:44.501486Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.501607Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.501642Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.501773Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.501825Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.502406Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.502490Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.502593Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.502654Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15531 }
2023-04-26T04:01:44.502708Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.502858Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.503328Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 851 }
2023-04-26T04:01:44.503764Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.503868Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 14556 }
2023-04-26T04:01:44.641676Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.641862Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.641931Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.642152Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.642267Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.643597Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.643753Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.644122Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.644247Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15569 }
2023-04-26T04:01:44.644345Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.644495Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.645446Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 813 }
2023-04-26T04:01:44.646289Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.646617Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 14526 }
2023-04-26T04:01:44.836142Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.836308Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.836356Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.836537Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.836627Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.837441Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.837528Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.837685Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.837763Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15638 }
2023-04-26T04:01:44.837828Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.838061Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.838897Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 744 }
2023-04-26T04:01:44.839567Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.839735Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 14911 }
2023-04-26T04:01:44.965813Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.965884Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.965902Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.965965Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.965993Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.966287Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.966355Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.966402Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.966427Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15641 }
2023-04-26T04:01:44.966438Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:44.966566Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.966862Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 741 }
2023-04-26T04:01:44.967005Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:44.967066Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 14911 }
2023-04-26T04:01:45.166676Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.166794Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.166843Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.166976Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.167043Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.168037Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.168198Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.168359Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.168441Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15829 }
2023-04-26T04:01:45.168502Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.168927Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.169460Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 553 }
2023-04-26T04:01:45.169876Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.170060Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15169 }
2023-04-26T04:01:45.308010Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.308313Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.308404Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.308725Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.308842Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.310438Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.311074Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.311338Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.311550Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.311738Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15661 }
2023-04-26T04:01:45.311924Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.312954Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 721 }
2023-04-26T04:01:45.314088Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.314307Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 14910 }
2023-04-26T04:01:45.435564Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.435689Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.435740Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.435874Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.435931Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.436857Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.436926Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.437009Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.437047Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15650 }
2023-04-26T04:01:45.437063Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.437467Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.438040Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 732 }
2023-04-26T04:01:45.438480Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.438653Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15077 }
2023-04-26T04:01:45.639763Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.639976Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.640055Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.640211Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.640277Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.641314Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.641426Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.641588Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.641692Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.641862Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15827 }
2023-04-26T04:01:45.642344Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.643210Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 555 }
2023-04-26T04:01:45.644075Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.644312Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15145 }
2023-04-26T04:01:45.777461Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.777624Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.777685Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.777868Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.777980Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.779864Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.780029Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.780252Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.780341Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15549 }
2023-04-26T04:01:45.780381Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.780932Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.782037Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 833 }
2023-04-26T04:01:45.783077Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.783426Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 14686 }
2023-04-26T04:01:45.971914Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.972095Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.972154Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.972346Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.972442Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.973938Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.974047Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.974196Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.974268Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:45.974389Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15778 }
2023-04-26T04:01:45.974992Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.975924Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 604 }
2023-04-26T04:01:45.976636Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:45.976894Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 14610 }
2023-04-26T04:01:46.099579Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.099708Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.099742Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.100041Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.100068Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.100546Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:46.100602Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.100668Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:46.100693Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 15000 }
2023-04-26T04:01:46.100705Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.100858Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:46.101279Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 1382 }
2023-04-26T04:01:46.101561Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:46.101620Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 13733 }
2023-04-26T04:01:46.228774Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.228861Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.228878Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.228958Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.228982Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.229353Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:46.229386Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.229421Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:46.229436Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 14958 }
2023-04-26T04:01:46.229446Z DEBUG Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(9) }
2023-04-26T04:01:46.229578Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:46.229779Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 1424 }
2023-04-26T04:01:46.230020Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 16384 }
2023-04-26T04:01:46.230071Z DEBUG Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(9), size_increment: 12081 }
```
